/* SELECT FIRST_NAME AS 직원명 
     ,  DEPARTMENT_ID AS 직급코드
     , SALARY AS 급여
     , DECODE(DEPARTMENT_ID,50,'8%',70,'7%',80,'5%','3%') AS 인상급여
FROM EMPLOYEES; */

SELECT DEPARTMENT_ID
     , SUM(SALARY) 합계
     , FLOOR(AVG(SALARY)) 평균
     , COUNT(*) 인원수
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID
HAVING AVG(SALARY) > 6000
ORDER BY DEPARTMENT_ID ASC;