UPDATE EMP_COMMISSION
   SET 커미션PCT = 0.6
   WHERE 사번 = 147;
  
UPDATE EMP_COMMISSION
  SET (급여, 커미션PCT) = (SELECT 급여, 커미션PCT FROM EMP_COMMISSION WHERE 사번 = 145)
  WHERE 사번 = 148;
COMMIT;   
SELECT * FROM EMP_COMMISSION;


SELECT * FROM 지출내역서_T;
INSERT INTO 지출내역서_T VALUES(SYSDATE,1000,0,'TEST',1,1);
SELECT * FROM 지출내역구분_T;
DELETE FROM 지출내역구분_T WHERE 구분ID=2;

ALTER TABLE 지출내역서_T DISABLE CONSTRAINT FK_지출내역서_T_ACCOUNT_TYPE CASCADE;--임시비활성화
ALTER TABLE 지출내역서_T ENABLE CONSTRAINT FK_지출내역서_T_ACCOUNT_TYPE;--다시활성화
--어지간하면 쓰지말것 

ALTER TABLE 지출내역서_T ADD CONSTRAINT FK_지출내역서_T_ACCOUNT_TYPE
                       FOREIGN KEY(ACCOUNT_TYPE) REFERENCES 지출내역구분_T(구분ID) ON DELETE SET NULL; --지워지면 NULL로 채움
SELECT * FROM USER_CONSTRAINTS WHERE TABLE_NAME = '지출내역서_T';

TRUNCATE TABLE 지출내역서_T; --지우고 롤백해도 복원이안됨.웬만하면 쓰지말것
