SELECT ROWNUM
     , EMPLOYEE_ID
     , FIRST_NAME
     , LAST_NAME
     , SALARY
     , COMMISSION_PCT
  FROM EMPLOYEES
 WHERE COMMISSION_PCT IS NOT NULL
   AND ROWNUM <=10
 ORDER BY SALARY DESC;
 
SELECT * 
     FROM ( SELECT EMPLOYEE_ID
                 , FIRST_NAME
                 , LAST_NAME
                 , SALARY
                 , COMMISSION_PCT 
              FROM EMPLOYEES 
              WHERE COMMISSION_PCT IS NOT NULL
              ORDER BY SALARY DESC)
     WHERE ROWNUM <=10;
     
  WITH EMP_COM
    AS(SELECT EMPLOYEE_ID
                 , FIRST_NAME
                 , LAST_NAME
                 , SALARY
                 , COMMISSION_PCT 
              FROM EMPLOYEES 
              WHERE COMMISSION_PCT IS NOT NULL
              ORDER BY SALARY DESC)
  SELECT * FROM EMP_COM;
  
 
  SELECT * 
     FROM(SELECT FIRST_NAME
               , LAST_NAME
               , DENSE_RANK() OVER(ORDER BY SALARY DESC) AS 순위
               FROM EMPLOYEES
               ORDER BY FIRST_NAME)
    WHERE 순위 <= 10;
   
   SELECT FIRST_NAME
        , LAST_NAME
        , SALARY
        , DENSE_RANK() OVER(ORDER BY SALARY DESC) AS 순위
      FROM EMPLOYEES;
     
     SELECT *
       FROM EMPLOYEES
      WHERE (SALARY, COMMISSION_PCT)= (SELECT SALARY, COMMISSION_PCT FROM EMPLOYEES WHERE EMPLOYEE_ID=157);
         SELECT *
       FROM EMPLOYEES
      WHERE (SALARY, COMMISSION_PCT)= ((9500, 0.35));        
     
          SELECT *
       FROM EMPLOYEES
      WHERE (SALARY, COMMISSION_PCT) IN ((9500,0.35),(9500,0.25));
 
 
 SELECT *
 FROM DEPARTMENTS ;

 SELECT *
    FROM EMPLOYEES, DEPARTMENTS
 WHERE EMPLOYEES.DEPARTMENT_ID =DEPARTMENTS.DEPARTMENT_ID ; 
  --오라클 전용

SELECT *
 FROM DEPARTMENTS ; 

SELECT *
 FROM EMPLOYEES;

 SELECT *
  FROM DEPARTMENTS, EMPLOYEES;
 
 
  SELECT *
   FROM EMPLOYEES
   JOIN DEPARTMENTS
  ON (EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID);
  -- ON 대신 USING(DEPARTMENT_ID) 도 사용가능()
  --표준 구문  
   SELECT *
   FROM EMPLOYEES
   JOIN DEPARTMENTS
  ON (EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID)
  WHERE EMPLOYEE_ID = 178; -- 178번이안나옴 조건에 맞는 것이 없기때문에.
  
 SELECT *
  FROM EMPLOYEES
  LEFT JOIN DEPARTMENTS -- 아웃터조인, 왼쪽 테이블에 포함이 안된 컬럼이 있으면 포함
  USING(DEPARTMENT_ID)
 WHERE EMPLOYEE_ID = 178;

SELECT * 
  FROM EMPLOYEES 
  RIGHT JOIN DEPARTMENTS --아우터조인,오른쪽 테이블에 포함이안된 컬럼이있으면 포함
  USING(DEPARTMENT_ID);
 
 SELECT *
   FROM EMPLOYEES
   FULL JOIN DEPARTMENTS --아우터조인,전부 포함
  USING(DEPARTMENT_ID);
 
 
SELECT *
 FROM EMPLOYEES E --AS붙이면안됨.
 JOIN DEPARTMENTS D
   ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
 JOIN JOBS J
   ON E.JOB_ID=J.JOB_ID
  WHERE E.COMMISSION_PCT IS NOT NULL
   AND D.DEPARTMENT_ID = 80;
 COMMIT;