
/*
* 1.EMPLOYEES 테이블을 조회 할 때 JOB_ID, DEPARTMENT_ID 컬럼의 ID가 아닌
* 식별 가능한 이름으로 조회 될 수 있도록 DEPARTMENTS, JOBS 테이블을 조인
* (서브쿼리도 사용 가능하기 때문에 서브쿼리로도 만들어 본다.)
* 
*/
SELECT * FROM EMPLOYEES e ;
SELECT * FROM DEPARTMENTS d ;
SELECT * FROM JOBS;

SELECT *
 FROM EMPLOYEES e
 JOIN JOBS j
  USING (JOB_ID)
 JOIN DEPARTMENTS d
  USING (DEPARTMENT_ID)
  ORDER BY EMPLOYEE_ID;
 
 /* 강사님 풀이(JOIN) SELECT E.EMPLOYEE_ID
       , E.FIRST_NAME
       , E.LAST_NAME
       , E.EMAIL
       , E.PHONE_NUMBER
       , E.HIRE_DATE
       , J.JOB_TITLE
       , E.SALARY
       , E.COMMISSION_PCT
       , E.MANAGER_ID
       , D.DEPARTMENT_NAME
  FROM EMPLOYEES E
  JOIN JOBS J
    ON E.JOB_ID = J.JOB_ID
  JOIN DEPARTMENTS D
   ON E.DEPARTMENT_ID = D.DEPARTMENT_ID;*/
 
  /*강사님 풀이 서브쿼리
  SELECT E.EMPLOYEE_ID
       , E.FIRST_NAME
       , E.LAST_NAME
       , E.EMAIL
       , E.PHONE_NUMBER
       , E.HIRE_DATE
       , (SELECT JOB_TITLE FROM JOBS J WHERE E.JOB_ID=J.JOB_ID) AS JOB_TITLE
       , E.SALARY
       , E.COMMISSION_PCT
       , E.MANAGER_ID
       , (SELECT DEPARTMENT_NAME FROM DEPARTMENTS D WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID) AS DEPARTMENT_NAME
  FROM EMPLOYEES E; */

/*
* 2.DEPARTMENTS 테이블과 LOCATIONS 테이블을 사용하여 각 부서가 어느지역에
* 위치하는지 JOIN 활용하여 조회한다.
* (서브쿼리도 사용 가능하기 때문에 서브쿼리로도 만들어 본다.)
*/

 SELECT * FROM DEPARTMENTS d;
SELECT * FROM LOCATIONS;

SELECT *
 FROM DEPARTMENTS d 
 JOIN LOCATIONS l
 ON d.LOCATION_ID = l.LOCATION_ID
 ORDER BY 1;


/* 강사님 풀이
 * SELECT D.DEPARTMENT_ID
 *      , D.DEPARTMENT_NAME
 *      , D.MANAGER_ID
 *      , L.LOCATION_ID
 *      , L.STREET_ADDRESS
 *      , L.POSTAL_CODE
 *      , L.CITY
 *      , L.STATE_PROVINCE
 *      , L.COUNTRY_ID
 *  FROM DEPARTMENTS D
 *  JOIN LOCATIONS L
 *    ON D.LOCATION_ID = L.LOCATION_ID;
 */
/*
* 3. 1번,2번 문제를 활용하여 지역별 사원 수를 구하시오
*/

SELECT DECODE((NVL(TO_CHAR(l.LOCATION_ID),'전체')),'1400','부천','1500','인천','1700','강남','1800','홍대','2400','건대','2500','혜화','2700','안양','전체') AS 지역번호
    ,  COUNT(*) AS 인원수   
 FROM EMPLOYEES e 
  JOIN JOBS j
  ON e.JOB_ID = j.JOB_ID
  JOIN DEPARTMENTS d 
  ON e.DEPARTMENT_ID = d.DEPARTMENT_ID 
  JOIN LOCATIONS l 
  ON d.LOCATION_ID =l.LOCATION_ID 
 GROUP BY ROLLUP(l.LOCATION_ID);

/* 강사님 풀이*/
  SELECT EMP_COUNT
       ,(SELECT DECODE(STATE_PROVINCE, NULL,' ',CONCAT(STATE_PROVINCE,' ')) || CITY '' || STREET_ADDRESS FROM LOCATIONS L WHERE L.LOCATION_ID = T.LOCATION_ID) AS ADDRESS
       FROM(SELECT COUNT(*) AS EMP_COUNT
              , L.LOCATION_ID
           FROM EMPLOYEES E
            JOIN JOBS J
              ON E.JOB_ID = J.JOB_ID
            JOIN DEPARTMENTS D
             ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
            JOIN LOCATIONS L
             ON D.LOCATION_ID=L.LOCATION_ID
       GROUP BY ROLLUP(L.LOCATION_ID)) T
*   ORDER BY 1 DESC NULLS LAST;


/*
* 4. COUNTRIES 테이블과 REGIONS 테이블 까지 추가로 사용하여 국가별, 대륙별 사원 수를
* 구하시오.
*/
SELECT * FROM REGIONS ;
SELECT * FROM COUNTRIES ;

SELECT NVL(TO_CHAR(r.REGION_ID),'전체') AS 대륙
    , NVL(TO_CHAR(c.COUNTRY_ID),'전체') AS 국가
    ,  COUNT(*) AS 인원수   
 FROM EMPLOYEES e 
  JOIN JOBS j
  ON E.SALARY BETWEEN j.MIN_SALARY AND j.MAX_SALARY 
              AND e.JOB_ID = j.JOB_ID
  JOIN DEPARTMENTS d 
  ON e.DEPARTMENT_ID = d.DEPARTMENT_ID 
  JOIN LOCATIONS l 
  ON d.LOCATION_ID =l.LOCATION_ID 
  JOIN COUNTRIES c
  ON l.COUNTRY_ID = c.COUNTRY_ID
  JOIN REGIONS r
  ON c.REGION_ID = r.REGION_ID
  GROUP BY ROLLUP(r.REGION_ID,c.COUNTRY_ID);
