CREATE TABLE SAMPLE(
      ID      NUMBER            PRIMARY KEY
    , NAME    VARCHAR2(30)      NOT NULL
    , GENDER  CHAR(1)           CHECK(GENDER IN ('F','M'))
    , AGE     NUMBER            DEFAULT(0) NOT NULL
    );
    
 INSERT INTO SAMPLE(ID,NAME,GENDER,AGE) VALUES(1,'홍길동','M',27);
 INSERT INTO SAMPLE(ID,NAME,GENDER,AGE) VALUES(2,'김주영','M',30);
 INSERT INTO SAMPLE(ID,NAME,GENDER    ) VALUES(3,'박수안','F'   );
 INSERT INTO SAMPLE(ID,NAME,GENDER,AGE) VALUES(4,'이종석','M',25);
INSERT INTO SAMPLE VALUES(5,'최설은','F',DEFAULT);

COMMIT;
SELECT * FROM SAMPLE;

SELECT * FROM USER_SYS_PRIVS;

CREATE OR REPLACE VIEW V_SAMPLE
  AS SELECT ID 
          , NAME
          , GENDER
          , DECODE(AGE,0,0,AGE - 2) AS AGE
         FROM SAMPLE;
        
SELECT * FROM V_SAMPLE ORDER BY ID;

DROP VIEW V_SAMPLE;

INSERT INTO V_SAMPLE VALUES('곽종수','F',30); --ID를 넣을 수 없음.PRIMART 키라 없으면 안됨
INSERT INTO V_SAMPLE VALUES(6,'곽종수','F'); -- AGE가 없어도 DEFAULT 값이 있어서 추가가능.
INSERT INTO V_SAMPLE VALUES(7,'김도연','F',23); --연산식이 들어 간것은 가상열이라서 사용할 수 없음.

SELECT * FROM USER_VIEWS; --뷰테이블 조회

CREATE OR REPLACE VIEW V_SAMPLE
  AS SELECT ID 
          , NAME
          , GENDER
          , AGE
         FROM SAMPLE
        WHERE AGE BETWEEN 20 AND 29
WITH CHECK OPTION;  

UPDATE V_SAMPLE
  SET AGE = 35
 WHERE ID =1; --VIEW의 CHECK옵션 위배(WHERE절에 작성된 검색조건이 CHECK옵션에 부여.)

 CREATE OR REPLACE VIEW V_SAMPLE
  AS SELECT ID 
          , NAME
          , GENDER
          , AGE
         FROM SAMPLE
        WHERE AGE BETWEEN 20 AND 29
WITH READ ONLY; --보기 용도로만 
GRANT CREATE SESSION TO puser1;




DROP SEQUENCE SEQ_SAMPLE;

CREATE SEQUENCE SEQ_TEST
 START WITH 300
 INCREMENT BY 5
 MAXVALUE 310
 MINVALUE 250
 CYCLE
 NOCACHE;
 
SELECT SEQ_TEST.NEXTVAL FROM DUAL; --다음번호 생성

SELECT SEQ_TEST.CURRVAL FROM DUAL; --최근번호 무엇

--시퀀스에 CACHE가 들어가있을경우 거기에 저장되어 껐다켰을경우 저장된곳부터? 잘모르겠음
--중간번호 날아감
--그냥 노캐쉬로쓰자~
--캐시를 쓰면 반복작업할때 효율좋아짐  알아보기.

SELECT * FROM USER_SEQUENCES WHERE SEQUENCE_NAME = 'SEQ_TEST'; 

CREATE SEQUENCE SEQ_SAMPLE START WITH 7 NOCACHE;

SELECT SEQ_SAMPLE.NEXTVAL FROM DUAL;
SELECT SEQ_SAMPLE.CURRVAL FROM DUAL;

SELECT * FROM SAMPLE ORDER BY ID;
INSERT INTO SAMPLE VALUES(SEQ_SAMPLE.NEXTVAL, '시퀀스', 'F', 0);
DELETE FROM SAMPLE WHERE ID = 8;

COMMIT;