--오라클전용 outer join, +붙임,+안붙인쪽 조인(왼쪽에 +면 right outer join)

--cross join

SELECT COUNT(*)
 FROM EMPLOYEES E
 CROSS JOIN DEPARTMENTS D;--ON 쓸필요 없음. 잘 안쓰임. 행X행 수


 
 
SELECT X, Y
     , (X*Y)
  FROM (SELECT(SELECT COUNT(*) FROM EMPLOYEES) AS X
     , (SELECT COUNT(*) FROM DEPARTMENTS) AS Y
   FROM DUAL);
   
  SELECT * FROM EMPLOYEES;
  SELECT * FROM JOBS;
 
 SELECT E.EMPLOYEE_ID
      , E.FIRST_NAME || ' ' || LAST_NAME
      , E.JOB_ID
      , J.JOB_ID
      , J.JOB_TITLE
      , E.SALARY
      , J.MIN_SALARY
      , J.MAX_SALARY
      FROM EMPLOYEES E
  JOIN JOBS J
    ON E.SALARY BETWEEN J.MIN_SALARY AND J.MAX_SALARY
    AND E.JOB_ID = J.JOB_ID
  ORDER BY 1;
 
 
 

 SELECT * FROM EMPLOYEES ORDER BY EMPLOYEE_ID ;

 SELECT E1.EMPLOYEE_ID
      , E1.FIRST_NAME || ' ' || E1.LAST_NAME
      , E2.EMPLOYEE_ID
      , E2.FIRST_NAME || ' ' || E2.LAST_NAME
      , E2.MANAGER_ID
    FROM EMPLOYEES E1
    JOIN EMPLOYEES E2
      ON E1.EMPLOYEE_ID = E2.MANAGER_ID
  ORDER BY E1.EMPLOYEE_ID;
 
 
 SELECT * FROM EMPLOYEES;

SELECT * FROM DEPARTMENTS;

SELECT * FROM JOBS;     


SELECT * FROM LOCATIONS;

SELECT * FROM COUNTRIES; 

SELECT * FROM REGIONS;


